### ISSUE TITLE
Using SoftwareSerial

### ISSUE THREAD

**Issue by Ddh012345dhD** [IndustrialShields/arduino-Tools40#13]
How to used SoftwareSerial for ModbusMaster?

**Comment by jordicasals** [comment]
Hello Dang Hung,

nowadays the ModbusRTU library only supports HardwareSerial due to the ModbusRTU protocol requirements. The default serial mode is 8E1 for ModbusRTU, and the SoftwareSerial is not able to support it by default.

According to this consideration, you can change all occurrences of HardwareSerial to SoftwareSerial. It should work.
