### ISSUE TITLE
ModbusRTU and SoftwareSerial

### ISSUE THREAD

**Issue by Gusev-Roman** [IndustrialShields/arduino-Tools40#6]
This library uses only HardwareSerial for ModbusRTU, but in some controllers, like ArdBox Analog HF connection between ESP32 and Arduino realized via SoftwareSerial, and so is a problem to using Modbus protocol between this two modules. Maybe you can rewrite class using AnySerial module?

**Comment by jordicasals** [comment]
Dear Gusev-Roman,

thank you very much for your suggestion.

The SoftwareSerial library is not able to support the ModbusRTU protocol, due to it can not be configured with the ModbusRTU default configuration: 8E1. Obviously you can use ModbusRTU with the 8N1 configuration, but I think that it is not the best option, because Modbus is not designed with this purpose. You can use a lightweight protocol, as SimpleComm (included in this library) or even a ligher one. Keep in mind that the communication between the Arduino Leonardo and the ESP32 in the ArdboxAnalogHF WiFi is an internal communication, and they can communicate in a simpler way than using the ModbusRTU library.

Again, thank you for your suggestion.
