### ISSUE TITLE
MODBUS TCP Slave no complila

### ISSUE THREAD

**Issue by frilovic** [IndustrialShields/arduino-Tools40#8]
In file included from C:\Users\win10N\Documents\Arduino\libraries\arduino-Tools40-master\examples\Modbus\ModbusTCPSlave\ModbusTCPSlave.ino:19:0:
C:\Users\win10N\Documents\Arduino\libraries\arduino-Tools40-master\src/ModbusTCPSlave.h:28:16: error: 'MODBUS_TCP_ADU_SIZE' was not declared in this scope
   uint8_t _adu[MODBUS_TCP_ADU_SIZE];
                ^~~~~~~~~~~~~~~~~~~
C:\Users\win10N\Documents\Arduino\libraries\arduino-Tools40-master\src/ModbusTCPSlave.h:28:16: note: suggested alternative: 'MODBUS_PDU_SIZE'
   uint8_t _adu[MODBUS_TCP_ADU_SIZE];
                ^~~~~~~~~~~~~~~~~~~
                MODBUS_PDU_SIZE
Se encontraron varias bibliotecas para "Ethernet.h"
Usado: C:\Users\win10N\Documents\Arduino\libraries\Ethernet
 No usado: C:\Program Files (x86)\Arduino\libraries\Ethernet
exit status 1
Error compilando para la tarjeta Arduino Mega or Mega 2560.

**Comment by jordicasals** [comment]
Hi frilovic,

first of all, thank you for using our libraries.

Nowadays, both the ModbusTCP libraries are only usable for Industrial Shields M-Duino devices. You can fork and modify the library to work in other devices. If you don't want to modify it, you can also [add the Industrial Shields devices into the Arduino IDE](https://www.industrialshields.com/blog/industrial-shields-blog-1/post/installing-the-industrial-shields-boards-in-the-arduino-ide-63) and use an M-Duino21+, instead of the Arduino Mega2560 to program it.
